runtime: java21
instance_class: F1

entrypoint: "java -jar your-travel-companion-0.0.1-SNAPSHOT.jar"




env_variables:
  DB_URL: jdbc:mysql://130.211.62.84:3306/travelcompanion?characterEncoding=utf8&serverTimezone=Europe/Kiev
  DB_USERNAME: travelcompanion-db
  DB_PASSWORD: password1
  GOOGLE_CLIENT_ID: 249068273473-5n24kqtsrbg7i1bvhfjv3hcb4gnqcpbj.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET: 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
  MAIL_USERNAME: olgapracticeprofile@gmail.com
  MAIL_PASSWORD: gblm ypjq ejvo fmnc

network:
  session_affinity: true

